export const DASHBOARD_ORDER_EVENT_CONSUMER = 'DASHBOARD_ORDER_EVENT_CONSUMER';
export const DASHBOARD_PAYMENT_EVENT_CONSUMER =
    'DASHBOARD_PAYMENT_EVENT_CONSUMER';
export const DASHBOARD_PROJECTION_REPOSITORY =
    'DASHBOARD_PROJECTION_REPOSITORY';
