export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const PASSWORD_RESET_TOKEN_REPOSITORY = Symbol(
    'PASSWORD_RESET_TOKEN_REPOSITORY',
);
export const PASSWORD_SERVICE = Symbol('PASSWORD_SERVICE');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const REFRESH_TOKEN_SERVICE = Symbol('REFRESH_TOKEN_SERVICE');
export const EMAIL_SERVICE = Symbol('EMAIL_SERVICE');
